name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: console6500/01-04-composite-actions-the-action@main
        with:
          PYTHON_VERSION: 3.8
